# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module 
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::af;

our %tailoring = 
    (
      standard => { rules => "& N <<< \x{149} " },
      types    => ["standard"],
      version  => 4126,
    );

1;
