# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module 
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::as;

our %tailoring = 
    (
      standard => {
                    rules => <<END,
& \x{994} < \x{982} < \x{981} < \x{983} 
& [before 1] \x{9A4} < \x{9A4}\x{9CD}\x{200D} 
& \x{9B9} < \x{995}\x{9CD}\x{9B7} 
END
                    settings => { normalization => "on" },
                  },
      types    => ["standard"],
      version  => 4126,
    );

1;
