# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::az;

our %tailoring = 
    (
      standard => {
                    rules => <<END,
& C < c\x{327} <<< C\x{327} 
& G < g\x{306} <<< G\x{306} 
& [before 1] i < \x{131} <<< I 
& i <<< \x{130} 
& O < o\x{308} <<< O\x{308} 
& S < s\x{327} <<< S\x{327} 
& U < u\x{308} <<< U\x{308} 
& K < q <<< Q 
& E < \x{259} <<< \x{18F} 
& H < x <<< X 
END
                  },
      types    => ["standard"],
      version  => 4126,
    );

1;
