# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::bn;

our %tailoring = 
    (
      standard => {
                    rules => <<END,
& \x{9FA} < \x{9F8} < \x{9F9} < \x{9F2} < \x{9F3} < \x{985} < \x{986} < \x{987} < \x{988} < \x{989} < \x{98A} < \x{98B} < \x{9E0} < \x{98C} < \x{9E1} < \x{98F} < \x{990} < \x{993} < \x{994} < \x{9BC} < \x{982} < \x{983} < \x{981} < \x{995} < \x{996} < \x{997} < \x{998} < \x{999} < \x{99A} < \x{99B} < \x{99C} < \x{99D} < \x{99E} < \x{99F} < \x{9A0} < \x{9A1} < \x{9DC} = \x{9A1}\x{9BC} < \x{9A2} < \x{9DD} = \x{9A2}\x{9BC} < \x{9A3} < \x{9CE} < \x{9A4} < \x{9A5} < \x{9A6} < \x{9A7} < \x{9A8} < \x{9AA} < \x{9AB} < \x{9AC} < \x{9AD} < \x{9AE} < \x{9AF} < \x{9DF} = \x{9AF}\x{9BC} < \x{9B0} < \x{9F0} < \x{9B2} < \x{9F1} < \x{9B6} < \x{9B7} < \x{9B8} < \x{9B9} < \x{9BD} < \x{9BE} < \x{9BF} < \x{9C0} < \x{9C1} < \x{9C2} < \x{9C3} < \x{9C4} < \x{9E2} < \x{9E3} < \x{9C7} < \x{9C8} < \x{9CB} = \x{9C7}\x{9BE} < \x{9CC} = \x{9C7}\x{9D7} < \x{9CD} < \x{9D7} 
END
                    settings => { normalization => "on" },
                  },
      types    => ["standard"],
      version  => 4126,
    );

1;
