# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::ca;

our %tailoring = 
    (
      standard => {
            rules => <<END,
& C < ch <<< Ch <<< CH 
& L < ll <<< l\xB7l <<< Ll <<< L\xB7l <<< LL <<< L\xB7L 
END
            settings => { backwards => "on" },
          },
      standard_cldrbug173 => { settings => { backwards => "on" } },
      standard_proposed => {
            rules => <<END,
& C < ch <<< cH <<< Ch <<< CH 
& L < ll <<< l\xB7l <<< lL <<< l\xB7L <<< Ll <<< L\xB7l <<< LL <<< L\xB7L 
END
            settings => { backwards => "on" },
          },
      types => ["standard", "standard_cldrbug173", "standard_proposed"],
      version => 4126,
    );

1;
