# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::cy;

our %tailoring = 
    (
      standard => {
                    rules => <<END,
& C < ch <<< cH <<< Ch <<< CH 
& D < dd <<< dD <<< Dd <<< DD 
& F < ff <<< fF <<< Ff <<< FF 
& G < ng <<< nG <<< Ng <<< NG 
& L < ll <<< lL <<< Ll <<< LL 
& P < ph <<< pH <<< Ph <<< PH 
& R < rh <<< rH <<< Rh <<< RH 
& T < th <<< tH <<< Th <<< TH 
END
                  },
      types    => ["standard"],
      version  => 4126,
    );

1;
