# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module 
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::de;

our %tailoring = 
    (
      phonebook => {
                     rules => <<END,
& a << \xE6 / e << \xE4 / e 
& A << \xC6 / E << \xC4 / E 
& \x{153} << \xF6 / e 
& \x{152} << \xD6 / E 
& u << \xFC / e 
& U << \xDC / E 
END
                   },
      standard  => { rules => "& ae << \xE6 <<< \xC6 " },
      types     => ["standard", "phonebook"],
      version   => 4126,
    );

1;
