# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::eo;

our %tailoring = 
    (
      standard => {
                    rules => <<END,
& C < \x{109} <<< \x{108} 
& G < \x{11D} <<< \x{11C} 
& H < \x{125} <<< \x{124} 
& J < \x{135} <<< \x{134} 
& S < \x{15D} <<< \x{15C} 
& U < \x{16D} <<< \x{16C} 
END
                  },
      types    => ["standard"],
      version  => 4126,
    );

1;
