# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::es;

our %tailoring = 
    (
      standard => { rules => "& N < n\x{303} <<< N\x{303} 
& ae << \xE6 <<< \xC6 " },
      traditional => {
            rules => <<END,
& N < n\x{303} <<< N\x{303} 
& C < ch <<< Ch <<< CH 
& l < ll <<< Ll <<< LL 
END
          },
      traditional_proposed => {
            rules => <<END,
& N < n\x{303} <<< N\x{303} 
& C < ch <<< cH <<< Ch <<< CH 
& l < ll <<< lL <<< Ll <<< LL 
END
          },
      types => ["standard", "traditional", "traditional_proposed"],
      version => 4126,
    );

1;
