# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::et;

our %tailoring = 
    (
      standard => {
                    rules => <<END,
& [before 1] T < \x{161} <<< \x{160} < z <<< Z < \x{17E} <<< \x{17D} 
& v << w <<< W 
& [before 1] X < \xF5 <<< \xD5 < \xE4 <<< \xC4 < \xF6 <<< \xD6 < \xFC <<< \xDC 
END
                  },
      types    => ["standard"],
      version  => 4126,
    );

1;
