# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::fa;

our %tailoring = 
    (
      standard => {
                    rules => <<END,
& \x{64E} << \x{650} << \x{64F} << \x{64B} << \x{64D} << \x{64C} 
& [before 1] \x{627} < \x{622} 
& \x{627} << \x{671} < \x{621} << \x{623} << \x{672} << \x{625} << \x{673} << \x{624} << \x{6CC}\x{654} <<< \x{649}\x{654} <<< \x{626} 
& \x{6A9} << \x{6AA} << \x{6AB} << \x{643} << \x{6AC} << \x{6AD} << \x{6AE} 
& \x{6CF} < \x{647} << \x{6D5} << \x{6C1} << \x{629} << \x{6C3} << \x{6C0} << \x{6BE} 
& \x{6CC} << \x{649} << \x{6D2} << \x{64A} << \x{6D0} << \x{6D1} << \x{6CD} << \x{6CE} 
END
                    settings => { normalization => "on" },
                  },
      types    => ["standard"],
      version  => 4126,
    );

1;
