# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module 
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::fi;

our %tailoring = 
    (
      default_type => "phonebook",
      phonebook => {
            rules => <<END,
& D \x{335} << \x{111} <<< \x{110} 
& G \x{335} << \x{1E5} <<< \x{1E4} 
& N \x{335} << \x{14B} <<< \x{14A} 
& T \x{335} << \x{167} <<< \x{166} 
& Y << \xFC <<< \xDC 
& Z \x{335} << \x{292} <<< \x{1B7} 
& \x{291} < \xE5 <<< \xC5 < \xE4 <<< \xC4 << \xE6 <<< \xC6 < \xF6 <<< \xD6 << \xF8 <<< \xD8 
END
          },
      standard => {
            rules => <<END,
& D << \xF0 <<< \xD0 << \x{111} <<< \x{110} 
& N << \x{14B} <<< \x{14A} 
& T << \xFE / h <<< \xDE / h 
& V << w <<< W 
& Y << \xFC <<< \xDC << \x{171} <<< \x{170} 
& [before 1] \x{292} < \xE5 <<< \xC5 < \xE4 <<< \xC4 << \xE6 <<< \xC6 < \xF6 <<< \xD6 << \xF8 <<< \xD8 << \x{151} <<< \x{150} << \xF5 <<< \xD5 << \x{153} <<< \x{152} 
END
          },
      standard_proposed => {
            rules => <<END,
& D \x{335} << \x{111} <<< \x{110} 
& G \x{335} << \x{1E5} <<< \x{1E4} 
& N \x{335} << \x{14B} <<< \x{14A} 
& T \x{335} << \x{167} <<< \x{166} 
& V << w <<< W 
& Y << \xFC <<< \xDC 
& Z \x{335} << \x{292} <<< \x{1B7} 
& \x{291} < \xE5 <<< \xC5 < \xE4 <<< \xC4 << \xE6 <<< \xC6 < \xF6 <<< \xD6 << \xF8 <<< \xD8 
END
          },
      types => ["phonebook", "standard", "standard_proposed"],
      version => 4126,
    );

1;
