# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module 
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::gu;

our %tailoring = 
    (
      standard => {
            rules => <<END,
& \x{AB9} < \x{ABC} < \x{A81} < \x{A82} < \x{A83} 
& \x{ABD} < \x{ACD} 
END
            settings => { normalization => "on" },
          },
      standard_proposed => {
            rules => <<END,
& \x{AD0} < \x{A82} << \x{A81} < \x{A83} 
& \x{AB9} < \x{AB3} 
END
            settings => { normalization => "on" },
          },
      types => ["standard", "standard_proposed"],
      version => 4126,
    );

1;
