# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module 
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::haw;

our %tailoring = 
    (
      standard => {
                    rules => <<END,
& a < e < i < o < u < h < k < l < m < n < p < w < \x{2BB} 
& a <<< A 
& e <<< E 
& i <<< I 
& o <<< O 
& u <<< U 
& h <<< H 
& k <<< K 
& l <<< L 
& m <<< M 
& n <<< N 
& p <<< P 
& w <<< W 
END
                  },
      types    => ["standard"],
      version  => 4126,
    );

1;
