# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module 
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::hi;

our %tailoring = 
    (
      direct => {
            rules => <<END,
& [last_non_ignorable] < \x{901} < \x{902} < \x{903} < \x{905} < \x{906} < \x{907} < \x{908} < \x{909} < \x{90A} < \x{90B} < \x{90C} < \x{90D} < \x{90E} < \x{90F} < \x{910} < \x{911} < \x{912} < \x{913} < \x{914} < \x{915} < \x{916} < \x{917} < \x{918} < \x{919} < \x{91A} < \x{91B} < \x{91C} < \x{91D} < \x{91E} < \x{91F} < \x{920} < \x{921} < \x{922} < \x{923} < \x{924} < \x{925} < \x{926} < \x{927} < \x{928} < \x{929} < \x{92A} < \x{92B} < \x{92C} < \x{92D} < \x{92E} < \x{92F} < \x{930} < \x{931} < \x{932} < \x{933} < \x{934} < \x{935} < \x{936} < \x{937} < \x{938} < \x{939} < \x{93C} < \x{93D} < \x{93E} < \x{93F} < \x{940} < \x{941} < \x{942} < \x{943} < \x{944} < \x{945} < \x{946} < \x{947} < \x{948} < \x{949} < \x{94A} < \x{94B} < \x{94C} < \x{94D} < \x{950} < \x{951} < \x{952} < \x{953} < \x{954} < \x{958} < \x{959} < \x{95A} < \x{95B} < \x{95C} < \x{95D} < \x{95E} < \x{95F} < \x{960} < \x{961} < \x{962} < \x{963} < \x{964} < \x{965} < \x{966} < \x{967} < \x{968} < \x{969} < \x{96A} < \x{96B} < \x{96C} < \x{96D} < \x{96E} < \x{96F} < \x{970} 
END
          },
      standard => {
            rules => <<END,
& [before 1] 0 < \x{950} < \x{964} < \x{965} < \x{970} 
& \x{939} < \x{93C} < \x{901} < \x{902} < \x{903} < \x{951} < \x{952} < \x{953} < \x{954} 
& \x{93D} < \x{94D} 
END
            settings => { normalization => "on" },
          },
      standard_proposed => {
            rules => <<END,
& \x{950} < \x{902} << \x{901} < \x{903} 
& \x{939} < \x{933} 
END
            settings => { normalization => "on" },
          },
      types => ["standard", "direct", "standard_proposed"],
      version => 4126,
    );

1;
