# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module 
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::hr;

our %tailoring = 
    (
      standard => {
            rules => <<END,
& C < \x{10D} <<< \x{10C} < \x{107} <<< \x{106} 
& D < d\x{17E} <<< D\x{17E} <<< D\x{17D} 
& L < lj <<< Lj <<< LJ 
& N < nj <<< Nj <<< NJ 
& S < \x{161} <<< \x{160} 
& Z < \x{17E} <<< \x{17D} 
END
          },
      standard_proposed => {
            rules => <<END,
& C < \x{10D} <<< \x{10C} < \x{107} <<< \x{106} 
& D < d\x{17E} = \x{1C6} <<< d\x{17D} <<< D\x{17E} = \x{1C5} <<< D\x{17D} = \x{1C4} < \x{111} <<< \x{110} 
& L < lj = \x{1C9} <<< lJ <<< Lj = \x{1C8} <<< LJ = \x{1C7} 
& N < nj = \x{1CC} <<< nJ <<< Nj = \x{1CB} <<< NJ = \x{1CA} 
& S < \x{161} <<< \x{160} 
& Z < \x{17E} <<< \x{17D} 
END
          },
      types => ["standard", "standard_proposed"],
      version => 4126,
    );

1;
