# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::hu;

our %tailoring = 
    (
      standard => {
            rules => <<END,
& C < cs <<< Cs <<< CS 
& D < dz <<< Dz <<< DZ 
& DZ < dzs <<< Dzs <<< DZS 
& G < gy <<< Gy <<< GY 
& L < ly <<< Ly <<< LY 
& N < ny <<< Ny <<< NY 
& S < sz <<< Sz <<< SZ 
& T < ty <<< Ty <<< TY 
& Z < zs <<< Zs <<< ZS 
& O < \xF6 <<< \xD6 << \x{151} <<< \x{150} 
& U < \xFC <<< \xDC << \x{171} <<< \x{170} 
& cs <<< ccs / cs 
& Cs <<< Ccs / cs 
& CS <<< CCS / CS 
& dz <<< ddz / dz 
& Dz <<< Ddz / dz 
& DZ <<< DDZ / DZ 
& dzs <<< ddzs / dzs 
& Dzs <<< Ddzs / dzs 
& DZS <<< DDZS / DZS 
& gy <<< ggy / gy 
& Gy <<< Ggy / gy 
& GY <<< GGY / GY 
& ly <<< lly / ly 
& Ly <<< Lly / ly 
& LY <<< LLY / LY 
& ny <<< nny / ny 
& Ny <<< Nny / ny 
& NY <<< NNY / NY 
& sz <<< ssz / sz 
& Sz <<< Ssz / sz 
& SZ <<< SSZ / SZ 
& ty <<< tty / ty 
& Ty <<< Tty / ty 
& TY <<< TTY / TY 
& zs <<< zzs / zs 
& Zs <<< Zzs / zs 
& ZS <<< ZZS / ZS 
END
          },
      standard_proposed => {
            rules => <<END,
& C < cs <<< cS <<< Cs <<< CS 
& D < dz <<< dZ <<< Dz <<< DZ 
& DZ < dzs <<< dzS <<< dZs <<< dZS <<< Dzs <<< DzS <<< DZs <<< DZS 
& G < gy <<< gY <<< Gy <<< GY 
& L < ly <<< lY <<< Ly <<< LY 
& N < ny <<< nY <<< Ny <<< NY 
& S < sz <<< sZ <<< Sz <<< SZ 
& T < ty <<< tY <<< Ty <<< TY 
& Z < zs <<< zS <<< Zs <<< ZS 
& O < \xF6 <<< \xD6 << \x{151} <<< \x{150} 
& U < \xFC <<< \xDC << \x{171} <<< \x{170} 
& cs <<< ccs / cs <<< ccS / cS <<< cCs / Cs <<< cCS / CS 
& Cs <<< Ccs / cs <<< CcS / cS <<< CCs / Cs 
& CS <<< CCS / CS 
& dz <<< ddz / dz <<< ddZ / dZ <<< dDz / Dz <<< dDZ / DZ 
& Dz <<< Ddz / dz <<< DdZ / dZ <<< DDz / Dz 
& DZ <<< DDZ / DZ 
& dzs <<< ddzs / dzs <<< ddzS / dzS <<< ddZs / dZs <<< ddZS / dZS <<< dDzs / Dzs <<< dDzS / DzS <<< dDZs / DZs <<< dDZS / DZS 
& Dzs <<< Ddzs / dzs <<< DdzS / dzS <<< DdZs / dZs <<< DdZS / dZS <<< DDzs / Dzs <<< DDzS / DzS <<< DDZs / DZs 
& DZS <<< DDZS / DZS 
& gy <<< ggy / gy <<< ggY / gY <<< gGy / Gy <<< gGY / GY 
& Gy <<< Ggy / gy <<< GgY / gY <<< GGy / Gy 
& GY <<< GGY / GY 
& ly <<< lly / ly <<< llY / lY <<< lLy / Ly <<< lLY / LY 
& Ly <<< Lly / ly <<< LlY / lY <<< LLy / Ly 
& LY <<< LLY / LY 
& ny <<< nny / ny <<< nnY / nY <<< nNy / Ny <<< nNY / NY 
& Ny <<< Nny / ny <<< NnY / nY <<< NNy / Ny 
& NY <<< NNY / NY 
& sz <<< ssz / sz <<< ssZ / sZ <<< sSz / Sz <<< sSZ / SZ 
& Sz <<< Ssz / sz <<< SsZ / sZ <<< SSz / Sz 
& SZ <<< SSZ / SZ 
& ty <<< tty / ty <<< ttY / tY <<< tTy / Ty <<< tTY / TY 
& Ty <<< Tty / ty <<< TtY / tY <<< TTy / Ty 
& TY <<< TTY / TY 
& zs <<< zzs / zs <<< zzS / zS <<< zZs / Zs <<< zZS / ZS 
& Zs <<< Zzs / zs <<< ZzS / zS <<< ZZs / Zs 
& ZS <<< ZZS / ZS 
END
          },
      types => ["standard", "standard_proposed"],
      version => 4126,
    );

1;
