# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::is;

our %tailoring = 
    (
      standard => {
                    rules => <<END,
& [before 1] b < \xE1 <<< \xC1 
& d << \x{111} <<< \x{110} < \xF0 <<< \xD0 
& [before 1] f < \xE9 <<< \xC9 
& [before 1] j < \xED <<< \xCD 
& [before 1] p < \xF3 <<< \xD3 
& [before 1] v < \xFA <<< \xDA 
& [before 1] z < \xFD <<< \xDD 
& [before 1] \x{292} < \xFE <<< \xDE < \xE6 <<< \xC6 << \xE4 <<< \xC4 < \xF6 <<< \xD6 << \xF8 <<< \xD8 < \xE5 <<< \xC5 
END
                  },
      types    => ["standard"],
      version  => 4126,
    );

1;
