# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module 
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::kk;

our %tailoring = 
    (
      standard => {
            rules => <<END,
& [before 1] \x{4AF} < \x{4B1} <<< \x{4B0} 
END
            settings => {
                  normalization => "on",
                  "suppress_contractions" => "[\x{400}-\x{45F}]",
                },
          },
      standard_proposed => {
            rules => <<END,
& [before 1] \x{43F} < \x{4E9} <<< \x{4E8} 
& [before 1] \x{4AF} < \x{4B1} <<< \x{4B0} 
& [before 1] \x{44C} < \x{456} <<< \x{406} 
END
            settings => {
                  normalization => "on",
                  "suppress_contractions" => "[\x{400}-\x{45F}]",
                },
          },
      types => ["standard", "standard_proposed"],
      version => 4126,
    );

1;
