# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::km;

our %tailoring = 
    (
      standard => {
                    rules => <<END,
& [last_tertiary_ignorable] = \x{17B4} = \x{17B5} 
& \x{17D4} < \x{17D7} < \x{17D3} < \x{17D4} < \x{17D5} < \x{17D6} < \x{17D8} < \x{17D9} < \x{17DA} < \x{17DC} 
& \x{17C8} << \x{17CE} << \x{17CF} << \x{17D1} << \x{17D0} << \x{17C8} << \x{17DD} << \x{17CB} << \x{17C9} << \x{17CA} << \x{17CD} 
& \x{179A} < \x{17AB} < \x{17AC} 
& \x{179B} < \x{17AD} < \x{17AE} 
& \x{179A}\x{17D2}\x{1780} << \x{1780}\x{17CC} 
& \x{179A}\x{17D2}\x{1781} << \x{1781}\x{17CC} 
& \x{179A}\x{17D2}\x{1782} << \x{1782}\x{17CC} 
& \x{179A}\x{17D2}\x{1783} << \x{1783}\x{17CC} 
& \x{179A}\x{17D2}\x{1784} << \x{1784}\x{17CC} 
& \x{179A}\x{17D2}\x{1785} << \x{1785}\x{17CC} 
& \x{179A}\x{17D2}\x{1786} << \x{1786}\x{17CC} 
& \x{179A}\x{17D2}\x{1787} << \x{1787}\x{17CC} 
& \x{179A}\x{17D2}\x{1788} << \x{1788}\x{17CC} 
& \x{179A}\x{17D2}\x{1789} << \x{1789}\x{17CC} 
& \x{179A}\x{17D2}\x{178A} << \x{178A}\x{17CC} 
& \x{179A}\x{17D2}\x{178B} << \x{178B}\x{17CC} 
& \x{179A}\x{17D2}\x{178C} << \x{178C}\x{17CC} 
& \x{179A}\x{17D2}\x{178D} << \x{178D}\x{17CC} 
& \x{179A}\x{17D2}\x{178E} << \x{178E}\x{17CC} 
& \x{179A}\x{17D2}\x{178F} << \x{178F}\x{17CC} 
& \x{179A}\x{17D2}\x{1790} << \x{1790}\x{17CC} 
& \x{179A}\x{17D2}\x{1791} << \x{1791}\x{17CC} 
& \x{179A}\x{17D2}\x{1792} << \x{1792}\x{17CC} 
& \x{179A}\x{17D2}\x{1793} << \x{1793}\x{17CC} 
& \x{179A}\x{17D2}\x{1794} << \x{1794}\x{17CC} 
& \x{179A}\x{17D2}\x{1795} << \x{1795}\x{17CC} 
& \x{179A}\x{17D2}\x{1796} << \x{1796}\x{17CC} 
& \x{179A}\x{17D2}\x{1797} << \x{1797}\x{17CC} 
& \x{179A}\x{17D2}\x{1798} << \x{1798}\x{17CC} 
& \x{179A}\x{17D2}\x{1799} << \x{1799}\x{17CC} 
& \x{179A}\x{17D2}\x{179A} << \x{179A}\x{17CC} 
& \x{179A}\x{17D2}\x{17AB} << \x{17AB}\x{17CC} 
& \x{179A}\x{17D2}\x{17AC} << \x{17AC}\x{17CC} 
& \x{179A}\x{17D2}\x{179B} << \x{179B}\x{17CC} 
& \x{179A}\x{17D2}\x{17AD} << \x{17AD}\x{17CC} 
& \x{179A}\x{17D2}\x{17AE} << \x{17AE}\x{17CC} 
& \x{179A}\x{17D2}\x{179C} << \x{179C}\x{17CC} 
& \x{179A}\x{17D2}\x{179D} << \x{179D}\x{17CC} 
& \x{179A}\x{17D2}\x{179E} << \x{179E}\x{17CC} 
& \x{179A}\x{17D2}\x{179F} << \x{179F}\x{17CC} 
& \x{179A}\x{17D2}\x{17A0} << \x{17A0}\x{17CC} 
& \x{179A}\x{17D2}\x{17A1} << \x{17A1}\x{17CC} 
& \x{179A}\x{17D2}\x{17A2} << \x{17A2}\x{17CC} <<< \x{17A3}\x{17CC} 
& \x{17A2} <<< \x{17A3} 
& \x{17A2}\x{17B6} = \x{17A4} 
& \x{17A2}\x{17B7} = \x{17A5} 
& \x{17A2}\x{17B8} = \x{17A6} 
& \x{17A2}\x{17BB} = \x{17A7} <<< \x{17A8} 
& \x{17A2}\x{17BC} = \x{17A9} 
& \x{17A2}\x{17BB}\x{17A2} = \x{17AA} 
& \x{17A2}\x{17C2} = \x{17AF} 
& \x{17A2}\x{17C3} = \x{17B0} 
& \x{17A2}\x{17C4} = \x{17B1} <<< \x{17B2} 
& \x{17A2}\x{17C5} = \x{17B3} 
& \x{17C5} < \x{17BB}\x{17C6} < \x{17C6} < \x{17B6}\x{17C6} < \x{17C7} 
END
                    settings => { normalization => "on" },
                  },
      types    => ["standard"],
      version  => 4126,
    );

1;
