# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module 
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::lv;

our %tailoring = 
    (
      standard => {
            rules => <<END,
& [before 1] D < \x{10D} <<< \x{10C} 
& [before 1] H < \x{123} <<< \x{122} 
& [before 1] J < y <<< Y 
& [before 1] L < \x{137} <<< \x{136} 
& [before 1] M < \x{13C} <<< \x{13B} 
& [before 1] O < \x{146} <<< \x{145} 
& [before 1] S < \x{157} <<< \x{156} 
& [before 1] T < \x{161} <<< \x{160} 
& [before 1] \x{1B7} < \x{17E} <<< \x{17D} 
END
          },
      standard_proposed => {
            rules => <<END,
& [before 1] D < \x{10D} <<< \x{10C} 
& [before 1] H < \x{123} <<< \x{122} 
& [before 1] L < \x{137} <<< \x{136} 
& [before 1] M < \x{13C} <<< \x{13B} 
& [before 1] O < \x{146} <<< \x{145} 
& [before 1] S < \x{157} <<< \x{156} 
& [before 1] T < \x{161} <<< \x{160} 
& [before 1] \x{1B7} < \x{17E} <<< \x{17D} 
END
          },
      types => ["standard", "standard_proposed"],
      version => 4126,
    );

1;
