# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::ml;

our %tailoring = 
    (
      standard => {
            rules => <<END,
& \x{D03} << \x{D3D} 
& \x{D4B} < \x{D57} 
& \x{D57} <<< \x{D4C} 
& \x{D39}  < \x{D33} 
& \x{D33}  < \x{D34} 
& \x{D34}  < \x{D31} 
& \x{D15}\x{D4D} << \x{D15}\x{D4D}\x{200D} 
& \x{D15}\x{D4D}\x{200D} <<< \x{D7F} 
& \x{D23}\x{D4D} << \x{D23}\x{D4D}\x{200D}  
& \x{D23}\x{D4D}\x{200D}  <<< \x{D7A} 
& \x{D28}\x{D4D} << \x{D28}\x{D4D}\x{200D} 
& \x{D28}\x{D4D}\x{200D} <<< \x{D7B} 
& \x{D30}\x{D4D} << \x{D30}\x{D4D}\x{200D} 
& \x{D30}\x{D4D}\x{200D} <<< \x{D7C} 
& \x{D32}\x{D4D} << \x{D32}\x{D4D}\x{200D} 
& \x{D32}\x{D4D}\x{200D} <<< \x{D7D} 
& \x{D33}\x{D4D} << \x{D33}\x{D4D}\x{200D} 
& \x{D33}\x{D4D}\x{200D} <<< \x{D7E} 
& \x{D2E}\x{D4D} << \x{D02} 
& \x{D28}\x{D4D} <<< \x{D7B}\x{D4D} 
END
          },
      standard_proposed => {
            rules => <<END,
& \x{D14} < \x{D02} < \x{D03} 
& \x{D39} < \x{D33} < \x{D34} 
& [before 1] \x{D15} < \x{D15}\x{D4D}\x{200D} 
& [before 1] \x{D23} < \x{D23}\x{D4D}\x{200D} 
& [before 1] \x{D28} < \x{D28}\x{D4D}\x{200D} 
& [before 1] \x{D31} < \x{D30}\x{D4D}\x{200D} = \x{D31}\x{D4D}\x{200D} 
& [before 1] \x{D32} < \x{D32}\x{D4D}\x{200D} 
& [before 1] \x{D33} < \x{D33}\x{D4D}\x{200D} 
END
            settings => { normalization => "on" },
          },
      types => ["standard", "standard_proposed"],
      version => 4126,
    );

1;
