# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module 
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::mr;

our %tailoring = 
    (
      standard => { settings => { normalization => "on" } },
      standard_proposed => {
            rules => <<END,
& \x{950} < \x{902} << \x{901} < \x{903} 
& \x{939} < \x{933} < \x{915}\x{94D}\x{937} < \x{91C}\x{94D}\x{91E} 
END
            settings => { normalization => "on" },
          },
      types => ["standard", "standard_proposed"],
      version => 4126,
    );

1;
