# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module 
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::mt;

our %tailoring = 
    (
      standard => {
                    rules => <<END,
& [before 1] d < \x{10A} <<< \x{10B} 
& [before 1] g < G\x{307} <<< g\x{307} 
& [before 1] h < G\x{126} <<< G\x{127} <<< g\x{126} <<< g\x{127} 
& [before 1] i < \x{126} <<< \x{127} 
& [before 1] z < Z\x{307} <<< z\x{307} 
END
                    settings => { caseFirst => "upper" },
                  },
      types    => ["standard"],
      version  => 4126,
    );

1;
