# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module 
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::or;

our %tailoring = 
    (
      standard => {
            rules => <<END,
& \x{B39} < \x{B15}\x{B4D}\x{B37} < \x{B5C} < \x{B5D} < \x{B5F} < \x{B71} < \x{B35} < \x{B02} < \x{B03} < \x{B01} < \x{B4D} < \x{B3C} 
END
            settings => { normalization => "on" },
          },
      standard_proposed => {
            rules => <<END,
& \x{B14} < \x{B02} < \x{B01} < \x{B03} 
& \x{B39} < \x{B15}\x{B4D}\x{B37} 
& \x{B2F} << \x{B5F} 
END
            settings => { normalization => "on" },
          },
      types => ["standard", "standard_proposed"],
      version => 4126,
    );

1;
