# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::pa;

our %tailoring = 
    (
      standard => { settings => { normalization => "on" } },
      standard_proposed => {
            rules => <<END,
& \x{A71} << \x{A70} << \x{A02} << \x{A01} << \x{A3C} 
& \x{A5C} < \x{A4D} 
END
            settings => { normalization => "on" },
          },
      types => ["standard", "standard_proposed"],
      version => 4126,
    );

1;
