# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::pl;

our %tailoring = 
    (
      standard => {
                    rules => <<END,
& A < \x{105} <<< \x{104} 
& C < \x{107} <<< \x{106} 
& E < \x{119} <<< \x{118} 
& L < \x{142} <<< \x{141} 
& N < \x{144} <<< \x{143} 
& O < \xF3 <<< \xD3 
& S < \x{15B} <<< \x{15A} 
& Z < \x{17A} <<< \x{179} < \x{17C} <<< \x{17B} 
END
                  },
      types    => ["standard"],
      version  => 4126,
    );

1;
