# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::ps;

our %tailoring = 
    (
      standard => {
                    rules => <<END,
& \x{64E} << \x{650} << \x{64F} << \x{64B} << \x{64D} << \x{64C} 
& [before 1] \x{627} < \x{622} 
& \x{627} << \x{623} << \x{672} << \x{671} << \x{625} << \x{673} < \x{621} 
& \x{62A} < \x{67C} << \x{679} 
& \x{62C} < \x{681} << \x{62D}\x{654} 
& \x{686} < \x{685} 
& \x{62F} < \x{689} << \x{688} 
& \x{631} < \x{693} << \x{691} 
& \x{698} < \x{696} 
& \x{6A9} << \x{6AA} << \x{643} 
& \x{6AB} << \x{6AF} 
& \x{6BC} << \x{6BB} 
& \x{648} << \x{624} << \x{6C7} << \x{6C9} 
& \x{647} <<< \x{6C0} <<< \x{647}\x{654} << \x{6D5} << \x{6C1} << \x{6BE} << \x{629} << \x{6C3} 
& \x{6CC} << \x{649} << \x{6D2} << \x{64A} << \x{6D0} << \x{6CD} << \x{6CC}\x{654} <<< \x{649}\x{654} <<< \x{626} 
& \xA0 << \x{200C} << \x{200D} 
END
                    settings => { normalization => "on" },
                  },
      types    => ["standard"],
      version  => 4126,
    );

1;
