# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module 
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::ro;

our %tailoring = 
    (
      standard => {
            rules => <<END,
& A < \x{103} <<< \x{102} < \xE2 <<< \xC2 
& D < \x{111} <<< \x{110} 
& I < \xEE <<< \xCE 
& S < \x{15F} = \x{219} <<< \x{15E} = \x{218} 
& T < \x{163} = \x{21B} <<< \x{162} = \x{21A} 
& Z < \x{17C} <<< \x{17B} 
END
          },
      standard_proposed => {
            rules => <<END,
& A < \x{103} <<< \x{102} < \xE2 <<< \xC2 
& I < \xEE <<< \xCE 
& S < \x{15F} = \x{219} <<< \x{15E} = \x{218} 
& T < \x{163} = \x{21B} <<< \x{162} = \x{21A} 
END
          },
      types => ["standard", "standard_proposed"],
      version => 4126,
    );

1;
