# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::ru;

our %tailoring = 
    (
      standard => {
                    settings => {
                          "suppress_contractions" => "[\x{400}-\x{417}\x{41A}-\x{437}\x{43A}-\x{45F}]",
                        },
                  },
      types    => ["standard"],
      version  => 4126,
    );

1;
