# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::si;

our %tailoring = 
    (
      dictionary => {
                      rules => <<END,
& \x{DF4} < \x{D85} 
& \x{D96} < \x{D82} < \x{D83} 
& \x{DF3} < \x{DCA} 
& \x{DD8} < \x{DF2} < \x{DDF} < \x{DF3} 
& \x{DA2}\x{DCA}\x{DA4} << \x{DA5} 
END
                      settings => { normalization => "on" },
                    },
      standard   => {
                      rules => <<END,
& \x{DF4} < \x{D85} 
& \x{D96} < \x{D82} < \x{D83} 
& \x{DF3} < \x{DCA} 
& \x{DD8} < \x{DF2} < \x{DDF} < \x{DF3} 
& \x{DA5} < \x{DA4} 
END
                      settings => { normalization => "on" },
                    },
      types      => ["standard", "dictionary"],
      version    => 4126,
    );

1;
