# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module 
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::sk;

our %tailoring = 
    (
      standard => {
            rules => <<END,
& A < a\x{308} <<< A\x{308} 
& C < c\x{30C} <<< C\x{30C} 
& D < \x{111} <<< \x{110} 
& H < ch <<< cH <<< Ch <<< CH 
& L < \x{142} <<< \x{141} 
& O < o\x{302} <<< O\x{302} 
& R < r\x{30C} <<< R\x{30C} 
& S < s\x{30C} <<< S\x{30C} 
& Z < z\x{30C} <<< Z\x{30C} < z\x{307} <<< Z\x{307} 
END
          },
      standard_proposed => {
            rules => <<END,
& A < a\x{308} <<< A\x{308} 
& C < c\x{30C} <<< C\x{30C} 
& H < ch <<< cH <<< Ch <<< CH 
& O < o\x{302} <<< O\x{302} 
& S < s\x{30C} <<< S\x{30C} 
& Z < z\x{30C} <<< Z\x{30C} 
END
          },
      types => ["standard", "standard_proposed"],
      version => 4126,
    );

1;
