# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::sl;

our %tailoring = 
    (
      standard => {
            rules => <<END,
& C < \x{10D} <<< \x{10C} < \x{107} <<< \x{106} 
& S < \x{161} <<< \x{160} 
& Z < \x{17E} <<< \x{17D} 
END
          },
      standard_proposed => {
            rules => <<END,
& C < \x{10D} <<< \x{10C} 
& S < \x{161} <<< \x{160} 
& Z < \x{17E} <<< \x{17D} 
END
          },
      types => ["standard", "standard_proposed"],
      version => 4126,
    );

1;
