# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::sq;

our %tailoring = 
    (
      standard => {
            rules => <<END,
& [before 1] D < \xE7 <<< \xC7 
& [before 1] E < dh <<< Dh <<< DH 
& [before 1] F < \xEB <<< \xCB 
& [before 1] H < gj <<< Gj <<< GJ 
& [before 1] M < ll <<< Ll <<< LL 
& [before 1] O < nj <<< Nj <<< NJ 
& [before 1] S < rr <<< Rr <<< RR 
& [before 1] T < sh <<< Sh <<< SH 
& [before 1] U < th <<< Th <<< TH 
& [before 1] Y < xh <<< Xh <<< XH 
& [before 1] \x{1B7} < zh <<< Zh <<< ZH 
END
          },
      standard_proposed => {
            rules => <<END,
& [before 1] D < \xE7 <<< \xC7 
& [before 1] E < dh <<< dH <<< Dh <<< DH 
& [before 1] F < \xEB <<< \xCB 
& [before 1] H < gj <<< gJ <<< Gj <<< GJ 
& [before 1] M < ll <<< lL <<< Ll <<< LL 
& [before 1] O < nj <<< nJ <<< Nj <<< NJ 
& [before 1] S < rr <<< rR <<< Rr <<< RR 
& [before 1] T < sh <<< sH <<< Sh <<< SH 
& [before 1] U < th <<< tH <<< Th <<< TH 
& [before 1] Y < xh <<< xH <<< Xh <<< XH 
& [before 1] \x{1B7} < zh <<< zH <<< Zh <<< ZH 
END
          },
      types => ["standard", "standard_proposed"],
      version => 4126,
    );

1;
