# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::sv;

our %tailoring = 
    (
      default_type => "reformed",
      reformed     => {
                        rules => <<END,
& D << \x{111} <<< \x{110} << \xF0 <<< \xD0 
& t <<< \xFE / h 
& T <<< \xDE / H 
& Y << u\x{308} <<< U\x{308} << u\x{30B} <<< U\x{30B} 
& [before 1] \x{292} < \xE5 <<< \xC5 < \xE4 <<< \xC4 << \xE6 <<< \xC6 << e\x{328} <<< E\x{328} < \xF6 <<< \xD6 << \xF8 <<< \xD8 << \x{151} <<< \x{150} << \x{153} <<< \x{152} << \xF4 <<< \xD4 
END
                      },
      standard     => {
                        rules => <<END,
& D << \x{111} <<< \x{110} << \xF0 <<< \xD0 
& t <<< \xFE / h 
& T <<< \xDE / H 
& v <<< w 
& V <<< W 
& Y << u\x{308} <<< U\x{308} << u\x{30B} <<< U\x{30B} 
& [before 1] \x{292} < \xE5 <<< \xC5 < \xE4 <<< \xC4 << \xE6 <<< \xC6 << e\x{328} <<< E\x{328} < \xF6 <<< \xD6 << \xF8 <<< \xD8 << \x{151} <<< \x{150} << \x{153} <<< \x{152} << \xF4 <<< \xD4 
END
                      },
      types        => ["standard", "reformed"],
      version      => 4126,
    );

1;
