# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module 
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::ta;

our %tailoring = 
    (
      standard => { settings => { normalization => "on" } },
      standard_proposed => {
            rules => <<END,
& \x{B66} << \x{BE6} 
& \x{B94} < \x{B82} < \x{B83} 
& \x{BB5} < \x{BB4} < \x{BB3} < \x{BB1} < \x{BA9} < \x{B9C} < \x{BB6} 
& \x{BB9} < \x{B95}\x{BCD}\x{BB7} 
& [before 1] \x{B95} < \x{B95}\x{BCD} 
& [before 1] \x{B99} < \x{B99}\x{BCD} 
& [before 1] \x{B9A} < \x{B9A}\x{BCD} 
& [before 1] \x{B9E} < \x{B9E}\x{BCD} 
& [before 1] \x{B9F} < \x{B9F}\x{BCD} 
& [before 1] \x{BA3} < \x{BA3}\x{BCD} 
& [before 1] \x{BA4} < \x{BA4}\x{BCD} 
& [before 1] \x{BA8} < \x{BA8}\x{BCD} 
& [before 1] \x{BAA} < \x{BAA}\x{BCD} 
& [before 1] \x{BAE} < \x{BAE}\x{BCD} 
& [before 1] \x{BAF} < \x{BAF}\x{BCD} 
& [before 1] \x{BB0} < \x{BB0}\x{BCD} 
& [before 1] \x{BB2} < \x{BB2}\x{BCD} 
& [before 1] \x{BB5} < \x{BB5}\x{BCD} 
& [before 1] \x{BB4} < \x{BB4}\x{BCD} 
& [before 1] \x{BB3} < \x{BB3}\x{BCD} 
& [before 1] \x{BB1} < \x{BB1}\x{BCD} 
& [before 1] \x{BA9} < \x{BA9}\x{BCD} 
& [before 1] \x{B9C} < \x{B9C}\x{BCD} 
& [before 1] \x{BB6} < \x{BB6}\x{BCD} 
& [before 1] \x{BB7} < \x{BB7}\x{BCD} 
& [before 1] \x{BB8} < \x{BB8}\x{BCD} 
& [before 1] \x{BB9} < \x{BB9}\x{BCD} 
& [before 1] \x{B95}\x{BCD}\x{BB7} < \x{B95}\x{BCD}\x{BB7}\x{BCD} 
END
            settings => { normalization => "on" },
          },
      types => ["standard", "standard_proposed"],
      version => 4126,
    );

1;
