# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module 
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::te;

our %tailoring = 
    (
      standard => {
            rules => <<END,
& \x{C39} < \x{C01} < \x{C02} < \x{C03} < \x{C4D} 
END
            settings => { normalization => "on" },
          },
      standard_proposed => {
            rules => <<END,
& \x{C14} < \x{C02} < \x{C01} < \x{C03} 
& \x{C39} < \x{C33} 
END
            settings => { normalization => "on" },
          },
      types => ["standard", "standard_proposed"],
      version => 4126,
    );

1;
