# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::th;

our %tailoring = 
    (
      default_type => "standard_proposed",
      standard => {
            rules => <<END,
& \x{E24} < \x{E24}\x{E45} 
& \x{E26} < \x{E26}\x{E45} 
& \x{E44} < \x{E45} 
& [before 2] \x{E47} << \x{E4E} 
& \x{E4B} << \x{E4C} << \x{E4D} 
& [last_secondary_ignorable] <<< [space] <<< - <<< . <<< ... <<< \x{E2F} <<< \x{E46} <<< \x{E4F} <<< \x{E5A} <<< \x{E5B} 
END
            settings => { normalization => "on" },
          },
      standard_proposed => {
            rules => <<END,
& [last_tertiary_ignorable] <<<< \x{E2F} <<<< \x{E46} <<<< \x{E4F} <<<< \x{E5A} <<<< \x{E5B} 
& \x{E4E} << \x{E4C} 
& \x{E2E} < \x{E4D} 
& \x{E32} <<< \x{E45} 
& \x{E44} < \x{E3A} 
END
            settings => { normalization => "on" },
          },
      types => ["standard", "standard_proposed"],
      version => 4126,
    );

1;
