# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module 
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::to;

our %tailoring = 
    (
      standard => {
                    rules => <<END,
& n < ng <<< Ng <<< NG <<< \x{14B} <<< \x{14A} 
& z < \x{2BB} <<< \x{2BD} 
& a << \x{101} <<< \xE1 <<< \x{100} <<< \xC1 
& e << \x{113} <<< \xE9 <<< \x{112} <<< \xC9 
& i << \x{12B} <<< \xED <<< \x{12A} <<< \xCD 
& o << \x{14D} <<< \xF3 <<< \x{14C} <<< \xD3 
& u << \x{16B} <<< \xFA <<< \x{16A} <<< \xDA 
END
                  },
      types    => ["standard"],
      version  => 4126,
    );

1;
