# This package was auto-generated by tools/cldr_generate.pl
# included in the forked distribution of the CPAN module 
# Unicode::Collate at http://github.com/fc7/Unicode-Collate
# using the collation data in CLDR version 1.8

package Unicode::Collate::Locale::ur;

our %tailoring = 
    (
      default_type => "standard",
      standard     => {
                        rules => <<END,
& \x{627} < \x{622} < \x{628} < \x{67E} < \x{62A} < \x{679} < \x{62B} < \x{62C} < \x{686} < \x{62D} < \x{62E} < \x{62F} < \x{688} < \x{630} < \x{631} < \x{691} < \x{632} < \x{698} < \x{633} < \x{634} < \x{635} < \x{636} < \x{637} < \x{638} < \x{639} < \x{63A} < \x{641} < \x{642} < \x{6A9} < \x{6AF} < \x{644} < \x{645} < \x{646} < \x{6BA} < \x{648} < \x{6C1} < \x{6CC} < \x{6C2} < \x{650}\x{6BE} < \x{6C3} < \x{621} < \x{626} < \x{6D2} 
& \x{650} << \x{64F} << \x{670} << \x{656} << \x{657} << \x{64B} << \x{64D} << \x{64C} << \x{654} << \x{651} << \x{658} << \x{653} 
& \x{610} <<< \x{611} <<< \x{612} <<< \x{613} <<< \x{614} <<< \x{64E} 
END
                      },
      types        => ["standard"],
      version      => 4126,
    );

1;
