--- #YAML:1.0
name:               Unicode-Collate
version:            0.53
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:          0
    constant:      0
    File::Spec:    0
    GDBM_File:     0
    Storable:      0
    strict:        0
    Test:          0
    Unicode::UCD:  0
    warnings:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
